import fs from 'fs-extra';
import inquirer from 'inquirer';
import yaml from 'js-yaml';
import path from 'path';
import pc from 'picocolors';
import {
  DEFAULT_REGISTER,
  SUPPORTED_AGENTS,
  SUPPORTED_FRAMEWORKS,
} from '../constants';
import { ConfigService } from '../services/ConfigService';
import { DetectionService } from '../services/DetectionService';
import { RegistryService } from '../services/RegistryService';

export class InitCommand {
  private detectionService = new DetectionService();
  private registryService = new RegistryService();
  private configService = new ConfigService();

  async run() {
    const configPath = path.join(process.cwd(), '.skillsrc');
    const detectionResults = await this.detectionService.detectFrameworks();
    const agentDetection = await this.detectionService.detectAgents();

    const anyAgentDetected = Object.values(agentDetection).some((d) => d);
    const shouldCheck = (id: string) =>
      anyAgentDetected ? agentDetection[id] : true;

    const { categories: supportedCategories, metadata } =
      await this.registryService.discoverRegistry(DEFAULT_REGISTER);

    const choices = SUPPORTED_FRAMEWORKS.map((f) => ({
      name: supportedCategories.includes(f.id)
        ? f.name
        : `${f.name} (Coming Soon)`,
      value: f.id,
    }));

    if (await fs.pathExists(configPath)) {
      const { overwrite } = await inquirer.prompt([
        {
          type: 'confirm',
          name: 'overwrite',
          message: '.skillsrc already exists. Do you want to overwrite it?',
          default: false,
        },
      ]);
      if (!overwrite) {
        console.log(pc.yellow('Aborted.'));
        return;
      }
    }

    const answers = await inquirer.prompt([
      {
        type: 'list',
        name: 'framework',
        message: 'Select Framework:',
        choices: choices,
        default:
          SUPPORTED_FRAMEWORKS.find((f) => detectionResults[f.id])?.id ||
          'flutter',
      },
      {
        type: 'checkbox',
        name: 'agents',
        message: 'Select AI Agents you use:',
        choices: SUPPORTED_AGENTS.map((a) => ({
          name: `${a.name} (${a.path}/)`,
          value: a.id,
          checked: shouldCheck(a.id),
        })),
      },
      {
        type: 'input',
        name: 'registry',
        message: 'Skills Registry URL:',
        default: DEFAULT_REGISTER,
      },
    ]);

    const frameworkId = answers.framework as string;
    const frameworkDef = SUPPORTED_FRAMEWORKS.find((f) => f.id === frameworkId);

    const config = this.configService.buildInitialConfig(
      frameworkId,
      answers.agents,
      answers.registry,
      metadata,
      frameworkDef?.languages || [],
    );

    const projectDeps = await this.detectionService.getProjectDeps();
    this.configService.applyDependencyExclusions(
      config,
      frameworkId,
      projectDeps,
    );

    const commentHeader = `# Auto-detected configuration generated by agent-skills-standard init
#
# Presence in 'skills' list = Active. To disable a skill, remove it from the list.
# 'exclude': IDs of sub-skills to skip during sync (auto-populated with undetected skills).
# 'custom_overrides': IDs of skills to PROTECT. Use this if you have modified a standard 
# skill locally and don't want the CLI to overwrite it.
#
# Run 'ags list-skills' to view all available skills.
`;
    await fs.writeFile(configPath, commentHeader + yaml.dump(config));

    console.log(pc.green('\n✅ Initialized .skillsrc with your preferences!'));
    console.log(pc.gray(`   Selected framework: ${frameworkId}`));
    console.log(
      pc.cyan(
        '\nNext step: Run `agent-skills-standard sync` to generate rule files.',
      ),
    );
  }
}
