import fs from 'fs';
import path from 'path';
import { Agent } from '../cli/src/constants/enums';
import { AGENT_CAPABILITIES, unsupportedSurfaces } from '../cli/src/capabilities/agentCapabilities';

const OUT = path.join(__dirname, '..', 'docs', 'agent-capabilities.md');
const dash = (v: string | null | undefined) => (v ? `\`${v}\`` : '—');

export function render(): string {
  const rows = Object.values(Agent).map((agent) => {
    const d = AGENT_CAPABILITIES[agent];
    const workflows = d.workflowFormat === 'none' ? '—' : `${d.workflowFormat} → \`${d.workflowPath}\``;
    const specialists = d.specialistFormat ? `${d.specialistFormat} → \`${d.agentPath}\`` : '—';
    const rules = d.ruleFileName ? `\`${d.ruleFileName}\`` : `\`${d.ruleFile}/*${d.ruleExtension}\``;
    const hooks = d.hookKind ? `${d.hookKind} → \`${d.hookScriptPath}\`` : '—';
    const mcp = d.mcp ? `${d.mcp.format ?? 'json'} → ${dash(d.mcp.projectFile)}` : '—';
    const cap = d.limits.skillBodyBytes ? `${d.limits.skillBodyBytes} B` : '—';
    const missing = unsupportedSurfaces(d).join(', ') || '—';
    return `| ${d.name} | \`${d.path}\` | ${workflows} | ${specialists} | ${rules} | ${hooks} | ${mcp} | ${cap} | ${missing} |`;
  });
  return [
    '# Agent Capabilities',
    '',
    '<!-- Generated by scripts/generate-capabilities-doc.ts from cli/src/capabilities/agentCapabilities.ts. Do not edit by hand; run `pnpm docs:capabilities`. -->',
    '',
    '| Agent | Skills | Workflows | Specialists | Rules | Hooks | MCP (project) | Skill body cap | Not supported |',
    '| --- | --- | --- | --- | --- | --- | --- | --- | --- |',
    ...rows,
    '',
  ].join('\n');
}

if (
  (typeof require !== 'undefined' && require.main === module) ||
  process.argv[1]?.includes('generate-capabilities-doc')
) {
  const next = render();
  if (process.argv.includes('--check')) {
    const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
    if (current !== next) {
      console.error('docs/agent-capabilities.md is out of date. Run `pnpm docs:capabilities`.');
      process.exit(1);
    }
    console.log('✅ docs/agent-capabilities.md is up to date.');
  } else {
    fs.writeFileSync(OUT, next);
    console.log('✅ Wrote docs/agent-capabilities.md');
  }
}
